### PR TITLE
T/38: Enabled items styling in the headings toolbar dropdown

### LINKED ISSUE #38: Style headings in the select box list
All options in the select box are right now listed in the same way. It would be nicer if the heading would have a stronger and bigger styling, making the hierarchy visually evident.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Styled items in the headings toolbar dropdown. Closes #38.

---

### Additional information

* Requires https://github.com/ckeditor/ckeditor5-heading/pull/58.
* Requires https://github.com/ckeditor/ckeditor5-ui/pull/163

### CODE REVIEW

**Comment by Reinmar** [comment]
Please squash the initial commits before we'll start the review.

**Comment by oleq** [comment]
The initial commits come from https://github.com/ckeditor/ckeditor5-heading/pull/58. Once the PR is resolved, things will simplify here.

**Comment by oleq** [comment]
image

**Comment by oleq** [comment]
There's a weird bug with dropdown positioning in Chrome when it's height is not an integer; it's positioned too low. I'll try to figure out what to do with it.

**Pull request merged**
