### PR TITLE
Docs: Improved title feature guide.

### LINKED ISSUE #133: Improve title feaure guide
As we talked with @AnnaTomanek, we should improve the title plugin guide. The editor there does not look like common title-body editors. We talked that we should use an inline editor instead of the classic editor.

### PR DESCRIPTION
**Pull request by pjasiun**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Improve title feature guide. Closes https://github.com/ckeditor/ckeditor5/issues/2467.

---

### Additional information

I replaced the classic editor with the inline editor and removed the heading from the content (I think it makes the title looks like another header). However, I think that this inline editor could be styled better. @dkonopka: could you help here?

### CODE REVIEW

**Comment by AnnaTomanek** [comment]
The current implementation with inline editor does not look any better - and it's not similar to any of the title-body editors (Slack posts, Grammarly, Medium etc.) that [you were referring to](https://github.com/ckeditor/ckeditor5/issues/2089#issuecomment-538985018). Plus due to our default styles, it's hard to notice there is even an editor there before you click :(

@dkonopka, any ideas on how to style this sample in a way that would resemble some recognized title-body editors?

**Comment by AnnaTomanek** [comment]
I added a sentence of explanation (with examples) to the guide. Perhaps this will make it more clear.

**Comment by dkonopka** [comment]
I've one doubt about it: **the content**, in my opinion, we should present a demo with visible placeholders - it will increase the discoverability of this plugin, to be honest. 

## Proposal v1
Screen Shot 2019-10-08 at 12 45 43

## Proposal v2
Screen Shot 2019-10-08 at 12 45 59

WDYT?

**Comment by pjasiun** [comment]
I agree with @dkonopka: the sample looks better without the content.

**Comment by AnnaTomanek** [comment]
I'm totally fine with it, we use the placeholders. Just note that all the other apps that we mentioned (Grammarly, Slack, Medium etc.) use some longer/more descriptive placeholders.

Screenshot 2019-10-08 at 13 02 28

Screenshot 2019-10-08 at 13 02 19

Screenshot 2019-10-08 at 13 01 48

**Comment by pjasiun** [comment]
Agree, I will create a ticket to make this placeholder configurable and use a better default placeholder. @AnnaTomanek: could you propose something nice for a default title and body placeholders?

**Comment by pjasiun** [comment]
-> https://github.com/ckeditor/ckeditor5-heading/issues/137

**Comment by Reinmar** [comment]
IMO, this looks bad. The toolbar is over proportional and is all greyed out. I'd rather propose a balloon + block toolbars here. Just like in Letters and similar to Grammarly, Slack and Medium mentioned above.

image

**Comment by pjasiun** [comment]
I changed the editor type to balloon-block, but now the pilcrow icon is outside the editor:

Screenshot 2019-10-09 at 14 27 37

@dkonopka Can you move the pilcrow icon inside?

**Pull request merged**
